---
updated: 2025-12-29
sources:
  settings_docs:
    repo: https://raw.githubusercontent.com/GyverLibs/Settings/main/docs
    files:
      - 1.main.md
      - 2.start.md
      - 3.builder.md
      - 4.widgets.md
      - 5.containers.md
      - 6.updates.md
      - 7.other.md
      - 8.custom.md
  settings_readme:
    repo: https://raw.githubusercontent.com/GyverLibs/Settings/main
    files:
      - README.md
      - README_EN.md
  deps_readme:
    repos:
      GTL: https://raw.githubusercontent.com/GyverLibs/GTL/main
      GyverDB: https://raw.githubusercontent.com/GyverLibs/GyverDB/main
      StringUtils: https://raw.githubusercontent.com/GyverLibs/StringUtils/main
      GyverHTTP: https://raw.githubusercontent.com/GyverLibs/GyverHTTP/main
      BSON: https://raw.githubusercontent.com/GyverLibs/BSON/main
      Stamp: https://raw.githubusercontent.com/GyverLibs/Stamp/main
      Table: https://raw.githubusercontent.com/GyverLibs/Table/main
      StreamIO: https://raw.githubusercontent.com/GyverLibs/StreamIO/main
      FOR_MACRO: https://raw.githubusercontent.com/GyverLibs/FOR_MACRO/main
      WiFiConnector: https://raw.githubusercontent.com/GyverLibs/WiFiConnector/main
    files:
      - README.md
      - library.properties
  local_project:
    path: .
    files:
      - platformio.ini
      - src/main.cpp
      - src/sets.cpp
      - src/sets.h
